[bot]
token = "token value"

[game]
path_to_keys = "../keys.csv"

[postgres]
host     = "host"
port     = 5432
user     = "user"
password = "password"
dbname   = "dbname"

[redis]
host = "redis"
port = 6379

[economy]
game_price = 100